accounts/urls.py
from django.urls import path
from .views import UserCreateView

urlpatterns = [
	path('signup/',UserCreateView.as_view(),name = 'signup'),

]

my_app/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
	path('',HomePageView.as_view(),name = 'home'),
	path('index/',IndexPageView.as_view(), name = 'index'),
	path('menu/',views.MenuPageView, name = 'menu'),
	path('about/',AboutPageView.as_view(), name = 'about'),
	path('book/',BookPageView, name = 'book'),
	path('product_create/',ProductCreateView.as_view(),name = 'product_create'),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('my_app.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

my_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
	name = models.CharField(max_length = 500)
	description = models.TextField()
	price = models.CharField(max_length = 100)
	image = models.ImageField(upload_to = 'image/')

	def __str__(self):
		return self.name


class Comment(models.Model):
	userName = models.CharField(max_length = 300, null = True)
	phone = models.CharField(max_length = 20)
	email = models.CharField(max_length = 50)
	message = models.TextField()
	date = models.DateTimeField(auto_now_add = True)


	def __str__(self):
		return f'{self.userName}'


# 1-bosqich
# Order yani mahsulotni savatga qushish uchun model
# from django.contrib.auth.models import User

class Order(models.Model):
	customer = models.ForeignKey(User, on_delete=models.SET_NULL,blank=True,null=True)
	date_orderd = models.DateTimeField(auto_now_add=True)
	name = models.CharField(max_length=200,null=True)
	complete =  models.BooleanField(default=False,null=True,blank=False)

	# pastdagi get_total funksiyasidan qaytagan qiymatni barcha
	# OrderItem(savatdagi mahsulotlar) larni hisoblash uchun

	@property # Dekorator
	def get_cart_total(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.get_total for item in orderitems])
		return total

	@property
	def get_cart_items(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.quantity for item in orderitems])
		return total

	# String obyektini qaytaradi	
	def __str__(self):
		return str(self.id)
# Mahsulotni qachon va kim totmonidan qaysi mahsulot qushilganligini saqlash uchun model
class OrderItem(models.Model):
	product = models.ForeignKey(Product, on_delete=models.SET_NULL,blank=True,null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL,blank=True,null=True)
	quantity = models.IntegerField(default=0,null=True,blank=True)
	date_added = models.DateTimeField(auto_now_add=True)



	# Mahsulot soniga qarab Kopaytirib beradi
	@property #Dekorator
	def get_total(self):
		total = self.product.price * self.quantity
		return total

	# String obyektini qaytaradi
	def __str__(self):
		return str(self.id)

# 2-bosqich
# ===> base.html ga 

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.urls import reverse_lazy


class UserCreateView(generic.CreateView):
	form_class = UserCreationForm
	template_name = 'signup.html'
	success_url = reverse_lazy('login')

my_app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView,CreateView
from .models import Product,Comment,Order
from django.core.paginator import Paginator
import requests
from django.urls import reverse_lazy


class HomePageView(TemplateView):
	template_name = 'home.html'

class IndexPageView(ListView):
	model = Product
	template_name = 'index.html'

# class MenuPageView(ListView):
# 	model = Product
# 	template_name = 'menu.html'
# 	context_object_name = 'maxsulotlar'


def MenuPageView(request):
	if request.user.is_authenticated:
		customer = request.user
		print(request.user)
		order, created = Order.objects.get_or_create(customer=customer,complete=False)
		items = order.orderitem_set.all()
		cartItems = order.get_cart_items # Savatdagi mahsulot nomi
	else:
		items = []
		order = {'get_cart_total': 0, "get_cart_items": 0}
		cartItems = order['get_cart_items']

	obj = Product.objects.all()
	page_n = request.GET.get('page',1)
	p = Paginator(obj,2)
	try:
		page = p.page(page_n)
	except Exception:
		page = p.page(1)
	context = {
	'page':page,
	'cartItems':cartItems
	}
	return render(request,'menu.html',context)

class AboutPageView(ListView):
	model = Product
	template_name = 'about.html'

class ProductCreateView(CreateView):
	model = Product
	template_name = 'product_create.html'
	# fields = ('mahsulot_nomi','mahsulot_tarkibi','mahsulot_rasmi','mahsulot_narxi')
	fields = '__all__'
	success_url = reverse_lazy('index')



def telegram_bot_sendtext(bot_message):
	bot_token = '5184089123:AAEH5YHYE3J0FHya9qTq8WNDUjOR2w8ETVk'
	bot_chatID = '1168299390'
	send_text = 'https://api.telegram.org/bot'+bot_token+'/sendMessage?chat_id='+bot_chatID+'&parse_mode=Markdown&text='+bot_message
	response = requests.get(send_text)
	return response.json()
# class BookPageView(ListView):
# 	model = Product
# 	template_name = 'book.html'

def BookPageView(request):
	if request.method == 'POST':
		name = request.POST.get('name',None)
		phone = request.POST.get('phone',None)
		email = request.POST.get('email',None)
		message = request.POST.get('message',None)
		user = Comment.objects.create(
			userName = name,
			phone = phone,
			email = email,
			message = message
			)
		user.save()

		telegram_bot_sendtext(f"Ismi:{user}\nEmail:{email}\nTel:{phone}\nXabar:{message}")

	return render(
	request = request,
	template_name = 'book.html'
		)

templates/about.html
{% extends 'base.html' %}

{% block content %}

  <section class="about_section layout_padding">
    <div class="container  ">

      <div class="row">
        <div class="col-md-6 ">
          <div class="img-box">
            <img src="images/about-img.png" alt="">
          </div>
        </div>
        <div class="col-md-6">
          <div class="detail-box">
            <div class="heading_container">
              <h2>
                We Are Feane
              </h2>
            </div>
            <p>
              There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration
              in some form, by injected humour, or randomised words which don't look even slightly believable. If you
              are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in
              the middle of text. All
            </p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
  
  
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<script type="text/javascript">
  var user = '{{  request.user }} '
  function getToken(name){
  var CookieValue = null;
  if (document.cookie && document.cookie !==''){
    var cookies = document.cookie.split(';');
    for (var i = 0; i<cookies.length; i++){
      var cookie = cookies[i].trim();
        if (cookie.substring(0,name.length +1) === (name + '=')){
          CookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
    }
  }
  return CookieValue
}
var csrftoken = getToken('csrftoken')
</script>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <style>
/* Style The Dropdown Button */

</style>
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="">

  <title> Feane </title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <!-- nice select  -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />
  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
  <link href="{% static 'css/csslar.css' %}" rel="stylesheet" />
<style>
  

</style>
</head>

<body>

  <div class="hero_area">
    <div class="bg-box">
      <img src="{% static 'images/hero-bg.jpg' %}" alt="">
    </div>
    <!-- header section strats -->
    <header class="header_section">
      <div class="container">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="index.html">
            <span>
              Feane
            </span>
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  mx-auto ">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'menu' %}">Menu</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'book' %}">Book Table</a>
              </li>
            </ul>
            <div class="user_option">
              {% if user.is_authenticated %}
              <div class="dropdown">
              <button class="dropbtn">{{ user.username|title }}</button><div class="dropdown-content">
                <a href="">Link 1</a>
                <a href="">Link 2</a>
                <a href="{% url 'logout' %}">Chiqish</a>
              </div>
            </div>
        <div>
          <a href="">
            <img id="cart-icon" src="{% static 'images/carts.png' %}">
          </a>
          <p id="cart-total">{{ cartItems }}</p>
        </div>
<style type="text/css">
  #cart-icon{
  width:49px;
  display: inline-block;
  margin-left: 15px;
  color: red;
  margin-top: 28px;
}
#cart-total{
  display: inline-table;
  text-align: center;
  color:#fff;
  background-color: red;
  width: 20px;
  height: 25px;
  border-radius: 50%;
  font-size: 14px;

}
</style>
              {% else %}
              <form class="form-inline ml-auto">
              <a href="{% url 'login' %}" class="order_online">
                Saytga kirish
              </a>
              <a href="{%  url 'signup' %}" class="order_online">
                Saytdan  ro'yxatdan o'tish
              </a>
              </form>
              {% endif %}
            </div>
          </div>
        </nav>
      </div>
    </header>

{% block content %}

{% endblock content %}

<!-- footer section -->
  <footer class="footer_section">
    <div class="container">
      <div class="row">
        <div class="col-md-4 footer-col">
          <div class="footer_contact">
            <h4>
              Contact Us
            </h4>
            <div class="contact_link_box">
              <a href="">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                  Location
                </span>
              </a>
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call +01 1234567890
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  demo@gmail.com
                </span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <div class="footer_detail">
            <a href="" class="footer-logo">
              Feane
            </a>
            <p>
              Necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with
            </p>
            <div class="footer_social">
              <a href="">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-linkedin" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-pinterest" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <h4>
            Opening Hours
          </h4>
          <p>
            Everyday
          </p>
          <p>
            10.00 Am -10.00 Pm
          </p>
        </div>
      </div>
      <div class="footer-info">
        <p>
          &copy; <span id="displayYear"></span> All Rights Reserved By
          <a href="https://html.design/">Free Html Templates</a><br><br>
          &copy; <span id="displayYear"></span> Distributed By
          <a href="https://themewagon.com/" target="_blank">ThemeWagon</a>
        </p>
      </div>
    </div>
  </footer>
  <!-- footer section -->

  <!-- jQery -->
  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <!-- bootstrap js -->
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <!-- owl slider -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <!-- isotope js -->
  <script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
  <!-- nice select -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
  <!-- custom js -->
  <script src="{% static 'js/custom.js' %}"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
  </script>
  <!-- End Google Map -->
<script src="{% static 'js/cart.js' %}"></script>
</body>

</html>

templates/book.html
 {% extends 'base.html' %}

 {% block content %}
  <section class="book_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          Book A Table
        </h2>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form_container">
            <form method="post">{% csrf_token %}
              <div>
                <input type="text" class="form-control"name = "name" placeholder="Ismingizni kiriting" />
              </div>
              <div>
                <input type="text" class="form-control"name = "phone" placeholder="Telefon raqamingizni kiriting:" />
              </div>
              <div>
                <input type="email" class="form-control"name = "email" placeholder="Emailingizni kiriting" />
              </div>
              <div>
                <div>
                <input type="text" class="form-control"name = "message" placeholder="Bizga xabaringiz" />
              </div>
              <div class="btn_box">
                <button>
                  Yuborish
                </button>
              </div>
            </form>
          </div>
        </div>
        <div class="col-md-6">
          <div class="map_container ">
            <div id="googleMap"></div>
          </div>
        </div>
      </div>
    </div>
  </section>


  {% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block content %}



{% endblock content %}

templates/product_create.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="">

  <title> Feane </title>


  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />


  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />

  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />


  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
<style>
  #soz{
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
  }

</style>
</head>

<body>

  <div class="hero_area">
    <div class="bg-box">
      <img src="{% static 'images/hero-bg.jpg' %}" alt="">
    </div>
    
    <header class="header_section">
      <div class="container">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="index.html">
            <span>
              Feane
            </span>
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="user_option">
              <a href="" class="user_link">
                <i class="fa fa-user" aria-hidden="true"></i>
              </a>
              <a class="cart_link" href="#">
                <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 456.029 456.029" style="enable-background:new 0 0 456.029 456.029;" xml:space="preserve">
                  <g>
                    <g>
                      <path d="M345.6,338.862c-29.184,0-53.248,23.552-53.248,53.248c0,29.184,23.552,53.248,53.248,53.248
                   c29.184,0,53.248-23.552,53.248-53.248C398.336,362.926,374.784,338.862,345.6,338.862z" />
                    </g>
                  </g>
                  <g>
                    <g>
                      <path d="M439.296,84.91c-1.024,0-2.56-0.512-4.096-0.512H112.64l-5.12-34.304C104.448,27.566,84.992,10.67,61.952,10.67H20.48
                   C9.216,10.67,0,19.886,0,31.15c0,11.264,9.216,20.48,20.48,20.48h41.472c2.56,0,4.608,2.048,5.12,4.608l31.744,216.064
                   c4.096,27.136,27.648,47.616,55.296,47.616h212.992c26.624,0,49.664-18.944,55.296-45.056l33.28-166.4
                   C457.728,97.71,450.56,86.958,439.296,84.91z" />
                    </g>
                  </g>
                  <g>
                    <g>
                      <path d="M215.04,389.55c-1.024-28.16-24.576-50.688-52.736-50.688c-29.696,1.536-52.224,26.112-51.2,55.296
                   c1.024,28.16,24.064,50.688,52.224,50.688h1.024C193.536,443.31,216.576,418.734,215.04,389.55z" />
                    </g>
                  </g>
                  <g>
                  </g>
                  <g>
                  </g>
                  <g>
                  </g>
                  <g>
                  </g>
                  <g>
                  </g>
                  <g>
                  </g>
                  <g>
                  </g>
                  <g>
                  </g>
                  <g>
                  </g>
                  <g>
                  </g>
                  <g>
                  </g>
                  <g>
                  </g>
                  <g>
                  </g>
                  <g>
                  </g>
                  <g>
                  </g>
                </svg>
              </a>
              <form class="form-inline">
                <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit">
                  <i class="fa fa-search" aria-hidden="true"></i>
                </button>
              </form>
            </div>
          </div>
        </nav>
      </div>
    </header>

<section class="book_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2 style="color: white;">
          Book A Table
        </h2>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form_container">
            <form method="post" enctype="multipart/form-data">{% csrf_token %}
              <div>
                <input type="text" class="form-control"name ="name" required="" id="id_name" placeholder="Mahsulot kiriting" />
              </div>
              <div>
                <input type="text" class="form-control"name ="description" required="" id="id_description" placeholder="Mahsulot tarkibi" />
              </div>

              <h2>
              	<style type="text/css">
              		input[type='file']{
              			color: transparent;
              		}
              	</style>
              	<input type="file" name="image" accept="image/*" required="" id="id_image">
              </h2>
              <div>
                <div>
                <input type="text" class="form-control"name ="price" required="" id="id_price" placeholder="Mahsulot narxi" />
              </div>
              <div class="btn_box">
                <button type="submit">
                  Yuborish
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
  <footer class="footer_section">
    <div class="container">
      <div class="row">
        <div class="col-md-4 footer-col">
          <div class="footer_contact">
            <h4>
              Contact Us
            </h4>
            <div class="contact_link_box">
              <a href="">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                  Location
                </span>
              </a>
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call +01 1234567890
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  demo@gmail.com
                </span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <div class="footer_detail">
            <a href="" class="footer-logo">
              Feane
            </a>
            <p>
              Necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with
            </p>
            <div class="footer_social">
              <a href="">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-linkedin" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-pinterest" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <h4>
            Opening Hours
          </h4>
          <p>
            Everyday
          </p>
          <p>
            10.00 Am -10.00 Pm
          </p>
        </div>
      </div>
      <div class="footer-info">
        <p>
          &copy; <span id="displayYear"></span> All Rights Reserved By
          <a href="https://html.design/">Free Html Templates</a><br><br>
          &copy; <span id="displayYear"></span> Distributed By
          <a href="https://themewagon.com/" target="_blank">ThemeWagon</a>
        </p>
      </div>
    </div>
  </footer>
  
  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
 
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
 
  <script src="{% static 'js/bootstrap.js' %}"></script>
 
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
 
  <script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
  
  <script src="{% static 'js/custom.js' %}"></script>
  
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
  </script>
  
</body>

</html>




<!-- <form method="post" enctype="multipart/form-data">

	{% csrf_token %}
	{{ form.as_p }}

	<button type="submit">Yuborish</button>
	


</form> -->


<!-- <input type="text" name="name" value="osh" maxlength="500" required="" id="id_name">
<textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>
<input type="text" name="price" value="25" maxlength="100" required="" id="id_price">
<input type="file" name="image" accept="image/*" required="" id="id_image"> -->